# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "rayspeed-asia"
client_id = "8bc2a9f35b9fcdcd0a22395ab1a9a5e3"
application_url = "https://returns-ncaa-surely-improve.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_shipping, read_shipping"

[auth]
redirect_urls = [
  "https://returns-ncaa-surely-improve.trycloudflare.com/auth/callback",
  "https://returns-ncaa-surely-improve.trycloudflare.com/auth/shopify/callback",
  "https://returns-ncaa-surely-improve.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "rayspeed-testing.myshopify.com"
